### PR TITLE
Minor UI fixes

### PR DESCRIPTION
**Pull request by nptr**
As a start, some minor UI fixes:
- Removed flickering of folder tree and file list with double buffering. The Win32 controls do support it but it isn't exposed to WinForms. Hence reflection and platform invoke..
- Added missing localization entries for the xbin editor. Always with the English text as placeholder. A proper translation is needed.

### CODE REVIEW

**Comment by Greavesy1899** [comment]
Nice changes to Game Explorer. Do you advise adding these UI fixes to other editors with long containers (such as map editor) or was it just an issue with the Game Explorer?

**Comment by nptr** [comment]
Yes, especially tree views and list views in resizable windows benefit greatly. I can make the fix for all of them if you'd like.
Can I open the map editor for M1DE as well? I haven't found it yet.

**Comment by Greavesy1899** [comment]
Sadly no. :(

It's only for Mafia II. You can open it by double clicking a "FrameResource_X.fr" file. In the future I hope to change this with a much more visible approach such as "Open Map Editor", then you can select which SDS to load.

**Comment by nptr** [comment]
I applied the changes to the rest of the tree views. Can't check if it had a visible effect since I only have M1DE for testing.
The XBIN editor did not benefit at least. Your decision whether/what to merge.

**Comment by Greavesy1899** [comment]
There is actually another significant list here -
Forms/Docking/DockSceneTree.Designer.cs

This uses a tree view for all loaded objects. After that one has been double buffered, I'll merge it.

**Comment by nptr** [comment]
Since I'm not really a fan of manually setting each control to double buffered, i went the inheritance way. Conveniently there is already a custom TreeView which i extended. I'm closing this PR now. My follow up PR is much cleaner: https://github.com/Greavesy1899/MafiaToolkit/pull/35

**Pull request closed without merging**
